allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  better-sqlite3: true
  prisma: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - prisma
  - unrs-resolver

onlyBuiltDependencies:
  - better-sqlite3
